#!/bin/sh
if [ -n "$(git status --porcelain | grep {in_file})" ]    # {appname} 
then    # {appname} 
    echo 'Запуск pre-commit хука: {appname} convert' 
    {appname} convert --in={in_file} --out={out_file} --dump={dump_file} {repo} && git add {out_file}
fi      # {appname}
