#!/bin/sh
if [ -n "$(git status --porcelain | grep {file})" ]    # {appname} 
then    # {appname} 
    echo 'Запуск pre-commit хука: {appname} convert' 
    {appname} convert --file '{file}' '{src}' && git add **/{file}
fi      # {appname}
